### ISSUE TITLE
-c [creation date] using current date

### ISSUE THREAD

**Issue by iburunat** [novoid/date2name#10]
I am using `date2name -c file.txt` and getting the current date prepended (2020-06-10), instead of the creation date. The file's creation date is 2013-08-13, and its modification date is 2020-06-08. I wonder whether I am doing something wrong (!). Thanks for any tips.

**Comment by novoid** [comment]
From the source code, it looks trivial so that I don't think that there should not be a major error. However, I also had an issue #6 with macOS in the past. Therefore, I need more input from your side.

Could you please report me your operating system + version and your Python version?

**Comment by iburunat** [comment]
Thanks! Yes, it seems my very same issue that one you referenced.
Here my details:
OS: 
`MacOS Catalina 10.15.14`

python3    (& python as well)
```
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by novoid** [comment]
... and you're using which version of `date2name`?

**Comment by iburunat** [comment]
Version is `date2name 2018-05-09`.

**Comment by novoid** [comment]
> Version is `date2name 2018-05-09`.

Well, then my suggestion is that you update `date2name` to a more recent version that most probably contains this issue from early 2019.
I now assume that this is the case, close the ticket and wish you all the best.
If this assumption is wrong, please re-open this issue after the update.

**Comment by iburunat** [comment]
Thanks. I actually installed this recently. In any case, I ran `pip install date2name --upgrade` and I am getting the message that this is the last version. I also did a `pip uninstall date2name` and reinstalled. Same result. I wonder what I am doing wrong.

**Comment by iburunat** [comment]
Ok, instead of using pip, I just copied `__init__.py` directly into the `~/anaconda3/bin/date2name `folder and it worked.

**Comment by novoid** [comment]
I don't know why the upgrade failed in your side. Your update command is correct AFAIK.
`2019.4.4.1` should be the current version installable via pip. Copying the `__init__.py` solves the issue technically as a dirty workaround.
I'd recommend trying to upgrade via `pip` in the future anyway.
