### ISSUE TITLE
note error retracting time stamp --withtime 

### ISSUE THREAD

**Issue by nbehrnd** [novoid/date2name#15]
`date2name` fails to revoke successfully the time stamp `--withtime` date2name prepends.

The version hosted on PyPi (May 9, 2018) does not understand (yet) `--remove` altogether when presenting a file in pattern of `2021-09-22_test.txt`.  The current version hosted on GitHub (commit `051254b`, Sep 20, 2021) recognizes `--remove` but truncates `2021-09-21T13.59.59_test.txt` only to `21T13.59.59_test.txt`; the anticipated pattern would be `test.txt`.

For documentation, the attached .zip contains `test_generator.org` from which `Makefile` and testing `test_date2name.py` are tangled.  To ease visual comparison in a file browser like Thunar while performing the tests, additional delays are set; this form of the `.org` thus is /not/ for inclusion in the in the project's Git history.

[2021-09-22_date2name.zip](https://github.com/novoid/date2name/files/7209903/2021-09-22_date2name.zip)

**Comment by nbehrnd** [comment]
Branch `retract` of my fork about `date2name`  ([here](https://github.com/nbehrnd/date2name/tree/retract)) now extends testing to trace the script's affect on files or folders to prepend the five fixed formats and how these stamps are removed.  Consistent with earlier observation, the difficulty to retract a `--withtime` stamp is met again for folders.

The current head in this branch still represents an early development version, aiming for a similar test coverage about files and tests.  In addition to the default *check across all test functions* the Makefile offers, the tests are marked.  Thus e.g., a call like

```bash
pytest-3 test_date2name.py -m "remove and folders"
```
constrains the scope of the tests performed to only 10 relevant (only `-r` and `--remove` for folders) out of a set of 110 test functions defined.  In this perspective, `test_generator.org` and its tangled files possibly are good enough for you/any other interested to improve how date/time stamps are removed.  All other tests implemented pass (i.e. in total, 4 fail, 116 pass; success rate .ge. 96%)

The part testing `date2name`'s action on *folders* repeats much of the part testing about *files*.  Perhaps I identify improvements for these series of tests relying on the permutation of parameters.  If filing a pull request, I probably should condense the changes of multiple individual commits into a single one; this is a technique I have to get familiar anyway.

**Comment by novoid** [comment]
Sounds great - thanks.

I have to admit that I'm not using `--remove` myself so far.

Looking forward for your pull request. To me, it doesn't matter. I'd gladly accept separate requests as well.

**Comment by nbehrnd** [comment]
The commits by 2021-11-25 resolve the problem, the issue is closed.
