### ISSUE TITLE
pip install does no longer install the script

### ISSUE THREAD

**Issue by kwbr** [novoid/date2name#25]
Previously `pipx install date2name` or `pip install --user date2name` installed the script for the user (in Linux) under `~/.local/bin`. Seems the upgrade to poetry broke this since no script is installed anymore. For example pipx gives the following error indicating that no script or binary is installed:

```
No apps associated with package date2name or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
```

Changing the the scripts section to use poetry solves this for me when installed locally:

```diff
-[project.scripts]
+[tool.poetry.scripts]
 date2name="date2name:main"
```

**Comment by nbehrnd** [comment]
@kwbr A bypass known to work (e.g., for Linux Debian) consists of 

- fetch file `date2name/__init__.py` as provided [on GitHub](https://github.com/novoid/date2name/blob/master/date2name/__init__.py)
- rename the local copy as `date2name`
- add the executable bit by `chmod +x` (because the file includes a shebang line)
- eventually move it manually to `usr/local/bin` (which requires elevated privileges)

Novice to `pipx` and glancing briefly its documentation in lines of «... an installation with `pipx` depends on `pip`...», is it possible to to stipulate a specific version to install, similar to `pip install date2name==2021.11.25.2` (the currently penultimate version)?

**Comment by nbehrnd** [comment]
@novoid Note though file `date2name/__init__.py` ([reference](https://github.com/novoid/date2name/blob/master/date2name/__init__.py)) was edited 2024-03-10, line 3 still reads

```
PROG_VERSION = u"Time-stamp: <2022-01-10 12:56:17 vk>"
```

**Comment by kwbr** [comment]
Yes this works because the program is only a single file. This is the workaround I used before patching my own version of `date2name.`

`pipx` uses `pip` under the hood and you can pin versions.

Unfortunately, also when using pure `pip` currently no binaries (scripts) are installed.

**Comment by nbehrnd** [comment]
@kwbr Possibly the success of installing `date2name` depends on the Linux distribution you use.

In an installation of Ubuntu 22.04 LTS/jammy I consider as «not too old»,* the installation with plain `pip` did not yield an error.  The optional flag `--nocorrections` was displayed in the help menu (one of the results of [5a60e7e](https://github.com/novoid/date2name/commit/5a60e7ea6c79e05fc11ff4607fff1f0a10419e26) by @novoid), and I consider it as successful *there*.  May you detail the OS you use?

\* A new LTS of Ubuntu 24.04 is scheduled to be released tomorrow, 2024-04-25.  Waiting for its first point release (somewhere summer/autumn 2024, then considering some bugfixes) before committing isn't wrong *per sé*.

[Xubuntu2204.log](https://github.com/novoid/date2name/files/15091910/Xubuntu2204.log)

**Comment by kwbr** [comment]
According to the provided logfile you are installing version 2021.11.25.2 which is not affected and not what this bug report is about.

Here is the output from `pip show` and you can clearly see that the script link is missing. 

```
(venv) ~/test-date2name-bug » pip show -f date2name
Name: date2name
Version: 2024.3.10.1
Summary: Handling time-stamps and date-stamps in file names
Home-page:
Author: Karl Voit
Author-email: tools@Karl-Voit.at
License: GPL v3
Location: /home/kai/test-date2name-bug/venv/lib/python3.11/site-packages
Requires:
Required-by:
Files:
  date2name-2024.3.10.1.dist-info/INSTALLER
  date2name-2024.3.10.1.dist-info/LICENSE.txt
  date2name-2024.3.10.1.dist-info/METADATA
  date2name-2024.3.10.1.dist-info/RECORD
  date2name-2024.3.10.1.dist-info/REQUESTED
  date2name-2024.3.10.1.dist-info/WHEEL
  date2name/__init__.py
  date2name/__pycache__/__init__.cpython-311.pyc
(venv) ~/test-date2name-bug » pip install date2name==2021.11.25.2
Collecting date2name==2021.11.25.2
  Using cached date2name-2021.11.25.2-py3-none-any.whl.metadata (2.7 kB)
Using cached date2name-2021.11.25.2-py3-none-any.whl (19 kB)
Installing collected packages: date2name
  Attempting uninstall: date2name
    Found existing installation: date2name 2024.3.10.1
    Uninstalling date2name-2024.3.10.1:
      Successfully uninstalled date2name-2024.3.10.1
Successfully installed date2name-2021.11.25.2
(venv) ~/test-date2name-bug » pip show -f date2name
Name: date2name
Version: 2021.11.25.2
Summary: Handling time-stamps and date-stamps in file names
Home-page: https://github.com/novoid/date2name
Author: Karl Voit
Author-email: tools@Karl-Voit.at
License: UNKNOWN
Location: /home/kai/test-date2name-bug/venv/lib/python3.11/site-packages
Requires:
Required-by:
Files:
  ../../../bin/date2name
  date2name-2021.11.25.2.dist-info/INSTALLER
  date2name-2021.11.25.2.dist-info/LICENSE.txt
  date2name-2021.11.25.2.dist-info/METADATA
  date2name-2021.11.25.2.dist-info/RECORD
  date2name-2021.11.25.2.dist-info/REQUESTED
  date2name-2021.11.25.2.dist-info/WHEEL
  date2name-2021.11.25.2.dist-info/entry_points.txt
  date2name-2021.11.25.2.dist-info/top_level.txt
  date2name/__init__.py
  date2name/__pycache__/__init__.cpython-311.pyc
(venv) ~/test-date2name-bug »
```

**Comment by nbehrnd** [comment]
@kwbr

- The update of the internal timestamps requires some sort of interaction by @novoid which perhaps fall flat this time.  Thus a more recent upload to PyPI, then installed with `pip` still may appear like an elder release when reading out the record in source code's `__init__.py`.
- Equally observed, the installation with a local .whl file still may fall flat if the version of the Python interpreter is less than 3.11.  For instance in said instance of Ubuntu 22.04 LTS
  
  ```shell
  sudo pip3.10 install ./date2name-2024.3.10.1-py3-none-any.whl 
  [sudo] password for norwid: 
  Processing ./date2name-2024.3.10.1-py3-none-any.whl
  ERROR: Package 'date2name' requires a different Python: 3.10.12 not in '<4.0,>=3.11'
  ```

- One can lower the requirement e.g., to Python 3.9 -- released 2020-10-05, its support will last till 2025 ([ref](https://www.python.org/downloads/)) and hence remove *this* particular obstacle during an installation (cf. the new log attached below), preferably complemented by an entry in the `~/.bashrc` file

  ```
  alias date2name="~/.local/lib/python3.11/site-packages/date2name/__init__.py"
  ```

  As a momentary *bypass* until @novoid can review and edit further pending PR (see #26) the other .zip archive includes both a .whl as well as a .tar.gz to try.

[2024-04-25_new_report.txt](https://github.com/novoid/date2name/files/15109813/2024-04-25_new_report.txt)
[2024-04-25_dist.zip](https://github.com/novoid/date2name/files/15109915/2024-04-25_dist.zip)

**Comment by novoid** [comment]
> @novoid Note though file `date2name/__init__.py` ([reference](https://github.com/novoid/date2name/blob/master/date2name/__init__.py)) was edited on 2024-03-10, line 3 still reads
> 
> ```
> PROG_VERSION = u"Time-stamp: <2022-01-10 12:56:17 vk>"
> ```

Background: The time-stamp is updated when the file is edited using GNU Emacs. When I change somethig quickly using vim or somebody else sends a PR without an updated time-stamp, I don't realize the unchanged time-stamp. :-(

**Comment by novoid** [comment]
> @kwbr Possibly the success of installing `date2name` depends on the Linux distribution you use.
> 
> In an installation of Ubuntu 22.04 LTS/jammy I consider as «not too old»,* the installation with plain `pip` did not yield an error. The optional flag `--nocorrections` was displayed in the help menu (one of the results of [5a60e7e](https://github.com/novoid/date2name/commit/5a60e7ea6c79e05fc11ff4607fff1f0a10419e26) by @novoid), and I consider it as successful _there_. May you detail the OS you use?
> 
> * A new LTS of Ubuntu 24.04 is scheduled to be released tomorrow, 2024-04-25. Waiting for its first point release (somewhere summer/autumn 2024, then considering some bugfixes) before committing isn't wrong _per sé_.
> 
> [Xubuntu2204.log](https://github.com/novoid/date2name/files/15091910/Xubuntu2204.log)

I'm using Debian stable and NixOS at the moment. Unfortunately, I don't have CI checks in place nor do I use the pip installation process myself. Therefore, this is error prone and I'm very happy when I get issues reported by you!

**Comment by novoid** [comment]
Damn, I used the wrong reference for my commit ;-)

It should be fixed with the latest commit. And I published to pypi.

**Comment by novoid** [comment]
Sorry for not fixing earlier - was a busy week for me and I'm on a business trip.

If there are further issues with the poetry-transition, please let me know.
