### ISSUE TITLE
current path

### ISSUE THREAD

**Issue by metbril** [novoid/date2name#27]
Using `date2name --dryrun .` (a dot for current path) appears to be renaming the current directory. I expected it to have the same behaviour as `date2name --dryrun *` (wildcard for all files). More or less like `ls .`. This probably is an edge case and OS controlled, but I at least wanted to let you know.

**Comment by novoid** [comment]
This is independent of "date2name".

If you are using the dot, your interactive shell replaces this with the current working directory before invoking the command.

If one of the CLI parameters of "date2name" is a directory, this directory gets its datestamp just as designed. If you want to address all the files within a directory, you need to use the shell syntax for that instead.
