### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jaguar** [novoid/date2name#5]
Add the ability to extract the EXIF data from images, and use that for the filename date on image files.

I noticed you use a bash script for your camera files, but it could be useful to have included in this script.

**Comment by novoid** [comment]
Hi jaguar,

There is [jhead](http://www.sentex.net/~mwandel/jhead/) for that purpose: `jhead "-nf%Y-%m-%dT%H.%M.%S_%f" *.jpg` does the trick.

Although I totally understand your intention, I am reluctant supporting file-content specific meta-data. If date2name would start supporting file-content specific meta-data it would end up in a hell of external dependencies: one for JPEG, one for MPEG video files, one for fitness tracker, and so forth. In contrast to that, I'd like to keep date2name simple, especially when there is a very good alternative like jhead.

HTH

**Comment by jaguar** [comment]
That makes sense, thanks for the tip for jhead, I will use that.  

I prefer the KISS method / Unix philosophy too. 

Thanks for all the tools.
