### ISSUE TITLE
organize

### ISSUE THREAD

**Issue by Gahamelas** [novoid/date2name#8]
Great tool, congrats. I was wondering if you knew https://organize.readthedocs.io/.
What would you say the advantage of your script is versus renaming using organize?
Thanks in advance. GM

**Comment by shivams** [comment]
Yes, I was also wondering the same. I also had [maid](https://github.com/benjaminoakes/maid) in mind. Both `organize` and `maid` are very versatile tools, and are mostly used for automating file archiving and organization. 

But both these tools don't provide any "methodology" or "principle" for file organization, whereas `date2name` provides that. But I think `date2name` should be combined as one tool with its other auxiliary utilities like `filetags` etc.

**Comment by Gahamelas** [comment]
Could you expand on what you mean "methodology"? I actually was trying to rename with organize using the created date, but I couldn't manage to find the right syntax. Maybe you know? ;)

**Comment by shivams** [comment]
## Methodology
By "methodology", I meant that these tools (`date2name` and `filetags`) propose that you organize your files by inserting meta-data into them; this metadata being ISO 8601 dates and tags. This simple addition to one's workflow can make the organization much better, as I am personally feeling (after a few day's usage). This is a better way of organizing files than the hierarchical organization using deeply nested folders as recent research has shown [1][2][3][4]

## `date2name` usage
The usage is well documented on the Readme page of the repo. So, say, you are inside a folder with many PDF files. You can rename them one-by-one or all in one go using:

```shell
#One by one:
date2name file1.pdf
date2name file2.pdf

#All in one go:
date2name *.pdf

#Using find to rename files using some filtering criterion:
find . -type f -size +10M -exec date2name {} \; #Rename files with size > 10 MB
find . -type f -iname "comics*pdf" -exec date2name {} \; #Rename PDF files with names beginning with comics
```


### References:
1.Dinneen, J. D. & Julien, C.-A. The ubiquitous digital file: A review of file management research. Journal of the Association for Information Science and Technology 71, E1–E32 (2020).
2.Alon, L. & Nachmias, R. Gaps between actual and ideal personal information management behavior. Computers in Human Behavior 107, 106292 (2020).
3.Geel, M. Memsy: A Personal Resource Management Infrastructure. 1 Band (ETH Zurich, 2015). doi:10.3929/ETHZ-A-010603237.
4.Voit, K. TagTrees: Improving Personal Information Management Using Associative Navigation.

**Comment by Gahamelas** [comment]
Great, I agree. But I haven't found a way to do that with organize.

**Comment by shivams** [comment]
For that, you should probably ask in the `organize`'s issues.

**Comment by Gahamelas** [comment]
I have, but no answer.

**Comment by shivams** [comment]
You can use `date2name` inside your `organize` config. E.g. you can define a rule such as this:

```yaml
rules:
  - folders: '~/Desktop'
    filters:
      - extension: pdf
    actions:
      - shell: 'date2name "{path}"'
```

Make sure to do a test run on a temporary folder to verify if it works for you.

**Comment by Gahamelas** [comment]
That's excellent, thank you! I hadn't thought of that!

**Comment by novoid** [comment]
> What would you say the advantage of your script is versus renaming using organize?

`date2name` has a very limited scope compared to organize. If you want to compare organize with tools I provide, then this would be:

- https://github.com/novoid/appendfilename
- https://github.com/novoid/guess-filename.py
- https://github.com/novoid/move2archive
- https://gist.github.com/novoid/c4a239abc4027ecfd14e9904da88e6a1

I personally prefer defining my rules within my tools rather than learning an artificial and still limiting definition language for the same purpose. However, I do see the use-case for organize. So the answer to your question is: personal preference.

It's a big advantage if you do have the free choice of tools here.

**Comment by Gahamelas** [comment]
Thanks. In Organize one can actually add python and shell code to the rules, so it's not limited at all. Either one could include your python funtions or write new ones in there.

**Comment by novoid** [comment]
@Gahamelas,
Thanks for clarification - good to know.
