### ISSUE TITLE
Rename based on EXIF creation date

### ISSUE THREAD

**Issue by iburunat** [novoid/date2name#9]
Excellent tool! I was wondering if you are planning on extending the rename functionality based on `EXIF` creation date (useful for media files).

**Comment by novoid** [comment]
Hello @iburunat,
I do have good news for you: there is already a proper tool that does that job:
`jhead "-nf%Y-%m-%dT%H.%M.%S_%f" *.jpg`

See https://www.sentex.ca/~mwandel/jhead/ for more information.

**Comment by iburunat** [comment]
As a good-news-appreciator, I am hereby forever beholden for this revelation!
